name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: "Дарова. Кажется это никто пилить не будет, по этому давай я помечу это в списочек на удаление, ладно? Спасибо, милашка!"
        days-before-stale: 31
        stale-pr-label: 'Залежалось'
        exempt-pr-label: 'Не удалять'
        exempt-issue-label: 'Не удалять'
